# docker compose file for mysql
version: '3.8'
services:
  harvest_hub_db:
    image: mysql
    container_name: harvest_hub_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: harvest_hub_dev
    volumes: 
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  dbdata:
